services:
  - type: web
    name: wishlist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        sync: false  # Persist across deploys
      - key: INVITE_TOKEN
        generateValue: true
      - key: DATABASE_URL
        sync: false # Will be set manually to Neon connection string
