services:
  - type: web
    name: wishlist
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///wishlist.db
